export const Multiplayer: string;
export const multiplayer: string;
export const appLogo: string;
export const appLogoSpin: string;
export const appHeader: string;
export const appTitle: string;
export const appIntro: string;
export const button: string;
export const counter: string;
